<!DOCTYPE validators [
<!ELEMENT validators (field|validator)+>

<!ELEMENT field (field-validator+)>
<!ATTLIST field
	name CDATA #REQUIRED
>

<!ELEMENT field-validator (param*, message)>
<!ATTLIST field-validator
	type CDATA #REQUIRED
    short-circuit (true|false) "false"
>

<!ELEMENT validator (param*, message)>
<!ATTLIST validator
	type CDATA #REQUIRED
    short-circuit (true|false) "false"
>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param
    name CDATA #REQUIRED
>

<!ELEMENT message (#PCDATA)>
<!ATTLIST message
    key CDATA #IMPLIED
>

]>
<!-- expanded with nsx-expanders:5.12.1, expansionResource net.democritus:Expanders:5.12.1 -->
<validators>
<!-- anchor:fieldValidators:start -->
  <field name='timeTask.name'>
    <field-validator type='conversion'>
      <param name='repopulateField'>true</param>
      <message>Conversion error</message>
    </field-validator>
  </field>
  <field name='timeTask.processor'>
    <field-validator type='conversion'>
      <param name='repopulateField'>true</param>
      <message>Conversion error</message>
    </field-validator>
  </field>
  <field name='timeTask.implementation'>
    <field-validator type='conversion'>
      <param name='repopulateField'>true</param>
      <message>Conversion error</message>
    </field-validator>
  </field>
  <field name='timeTask.params'>
    <field-validator type='conversion'>
      <param name='repopulateField'>true</param>
      <message>Conversion error</message>
    </field-validator>
  </field>
  <field name='timeTask.triggerState'>
    <field-validator type='conversion'>
      <param name='repopulateField'>true</param>
      <message>Conversion error</message>
    </field-validator>
  </field>
  <field name='timeTask.intervalPeriod'>
    <field-validator type='conversion'>
      <param name='repopulateField'>true</param>
      <message>Conversion error</message>
    </field-validator>
  </field>
  <field name='timeTask.requiredAction'>
    <field-validator type='conversion'>
      <param name='repopulateField'>true</param>
      <message>Conversion error</message>
    </field-validator>
  </field>
<!-- anchor:fieldValidators:end -->
</validators>
